name: Pokerank-api Deployment to CPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to CPanel via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Go to project folder on server
            cd ~/devops/PokeRank-backend-development/pokerank-api/

             # PM2: Delete old process if exists, start new
            pm2 delete pokerank-api || true
            pm2 start "npm run start:prod" --name pokerank-api
            pm2 save
