name: Pokerank-api Restart Only

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Restart app via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/stagingserver/devops/PokeRank-backend-development/pokerank-api

            # Delete old PM2 process
            pm2 delete pokerank-api || true

            # Start new process
            pm2 start "npm run start:prod" --name pokerank-api

            pm2 save
